name: mixlify
description: A unified messaging application based on Matrix protocol.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  flutter_secure_storage: ^9.0.0
  matrix: ^0.22.5
  emoji_picker_flutter: ^1.6.3
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
